replicaCount: 1
image:
  repository: confy
  tag: 1.0-b211111eb1
  pullPolicy: IfNotPresent

service:
  name: confy
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

resources:
#  limits:
#    cpu: 300m
#    memory: 512Mi
#  requests:
#    cpu: 300m
#    memory: 512Mi

